"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var card_1 = require("../controllers/card");
var router = (0, express_1.default)();
router.get('/cards', card_1.getCards);
router.post('/cards', card_1.createCard);
router.delete('/cards/:id', card_1.deleteCardById);
router.put('/cards/:cardId/likes', card_1.likeCard);
router.delete('/cards/:cardId/likes', card_1.unlikeCard);
exports.default = router;
